// <auto-generated />
using System;
using AccountService.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223231720_AddIndexesAndConfig")]
    partial class AddIndexesAndConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountService.Domain.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("divisa");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activa")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_cuenta");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_cuenta");

                    b.HasKey("IdCuenta")
                        .HasName("p_k_bank_accounts");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("i_x_bank_accounts_id_usuario");

                    b.HasIndex("NumeroCuenta")
                        .IsUnique()
                        .HasDatabaseName("i_x_bank_accounts_numero_cuenta");

                    b.ToTable("bank_accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
